### ISSUE TITLE
Centralize input control into a GameInputManager

### ISSUE THREAD

**Issue by DavieCakes** [DavieCakes/2DGame#15]
Another design enhancement that would be nice to have **if** this were a project that was going to keep growing.

Input control is handled in a few different places, having a system that centralizes this would be fantastic, but probably difficult to design at first. We'd need to find a way for a GameObject to 'checkout' some input functionality and send a delegate or interface implementation up to the game input manager so it knows to call a function when that checked-out input occurs. We'd also need some sort of priority system when multiple input's are checked-out (like a stack, when most recent 'checkout' is logged on top, then on pop that input functionality gets released to the lower gameObjects on the stack again. You can imagine walking in the world uses WASD, but then an encounter occurs and it wants WASD to navigate the menu...).

Low priority, because it would be 'nice to have'. I just really enjoy thinking about software design.

**Comment by AsewAsew** [comment]
Unity already does this using the built in "Input" class, which is what I was using. There isn't really a more efficient way of doing this. The only thing that would need to happen is that when a UI opens, the player's movement would need to be paused and unpaused when closed.

Side note, WASD does move through menus (battle/main/pause at least) already. The only other UI that would need it implemented in would be Inventory UI. Arrow keys work the same way as WASD.

**Comment by DavieCakes** [comment]
Oh I see, awesome! I'll have to look closer at the Input class. I know it works already, I'm just thinking of alternatives to each component handling it's own input code in different manners, it would be nice to do this in one place, but maybe I'm just over thinking it.
